### PR TITLE
Add all files related to 3D printing the Ultracortex MarkIV, named properly.

### PR DESCRIPTION
**Pull request by VIVelev**
This PR is a fix to [Issue #237 in OpenBCI/Docs](https://github.com/OpenBCI/Docs/issues/237).

### CODE REVIEW

**Comment by retiutut** [comment]
What about the original files?

**Comment by VIVelev** [comment]
They are all there under STL. Just splitted into frames/full, frames/halves, frames/quads.
And the rest just under STL (board mount, board cover, clips, inserts)

**Comment by retiutut** [comment]
well i think you can delete the misnamed files if you've set everything up in a new directory here

**Comment by retiutut** [comment]
hmm i was expecting to see negative code here.

**Comment by VIVelev** [comment]
Which are the misnamed files?

**Comment by VIVelev** [comment]
I think all is fine. I have correctly named all the files now.

**Comment by retiutut** [comment]
Awesome! I'll get someone from the office to check this tomorrow. Thank you!

**Pull request closed without merging**
